version: "3"
services:

  mongo:
    image: mongo:4
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: factory!root
    expose:
      - 27017
    ports:
      - 20177:27017
    command: -f /etc/mongod.conf
  #    configs:
  #      - /etc/mongod.conf
    volumes:
  #      - ./mongo/db:/data/db
  #      - ./mongo/conf/mongod.conf:/etc/mongod.conf
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/mongod.key:/etc/mongod.key
      - mongo:/data/db

  mongo-second:
    image: mongo:4
    restart: always
    container_name: mongo-second
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: root
  #      MONGO_INITDB_ROOT_PASSWORD: factory!root
    expose:
      - 27017
    ports:
      - 20178:27017
    command: -f /etc/mongod.conf
    volumes:
  #      - ./mongo/db:/data/db
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/mongod.key:/etc/mongod.key
      - mongo2:/data/db
    depends_on:
      - mongo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      # - http.cors.enabled=true
      # - http.cors.allow-origin=http://localhost:8090
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-db:/usr/share/elasticsearch/data

  monstache:
    image: rwynn/monstache:rel6
    container_name: monstache
    command: -f /monstache.config.toml &
    volumes:
      - ./elasticsearch/config/monstache.config.toml:/monstache.config.toml
    depends_on:
      - elasticsearch
      - mongo
      - mongo-second
    links:
      - "elasticsearch"
    ports:
      - 8088:8080

  mongosetup:
    image: setup-rspl
    build: ./setup-rspl/
    depends_on:
      - mongo
      - mongo-second
    links:
      - "mongo"

volumes:
  mongo:
  mongo2:
  elasticsearch-db:
